name: Test Secret Workflow

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print Secret Message
        env:
          SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}
        run: |
          echo "Mensaje de secreto: $SECRET_MESSAGE"
